import { chat, hashMessage } from "./dBSetup.js"

/**
 * Function to log chat details to the database
 * @param {string} conversationId - Unique identifier for the chat session
 * @param {string} userMessage - The message sent by the user
 * @param {string} llmResponse - The response generated by the LLM
 * @param {number} startTime - Timestamp when the user message was sent
 * @param {number} replyTime - Timestamp when the LLM response was received
 * @param {string} modelName - Name of the LLM model used
 * @param {object} options - Optional parameters including tokenUsage, and apiParams
 */
export async function logChat(

    conversationId,
    userMessage,
    llmResponse,
    startTime,
    replyTime,
    modelName,
    options = {}
) {
    try {
        // Hash the userMessage and llmResponse for privacy
        // Uses the hashMessage function imported from dBSetup.js
        const hashedUser = hashMessage(userMessage, process.env.MESSAGE_HASH_KEY);
        const hashedLLM = hashMessage (llmResponse, process.env.MESSAGE_HASH_KEY)

        const chatDoc  = new chat({
            conversationId,
            userMessage: {
                raw: userMessage,
                hashed: hashedUser,
                timeStamp: startTime,
            },
            llmResponse: {
                raw: llmResponse,
                hashed: hashedLLM,
                timeStamp: replyTime,
            },
            tokenUsage: options.tokenUsage || {},
            modelName: modelName,
            apiParams: options.apiParams || {},
        });
        
        // Save the chat document to the database
        await chatDoc.save();
        console.log(`Chat logged: ${chatDoc.messageId}`);

    } catch(err) {

        // Log any errors that occur during the logging process
        // If there is an error, log it and exit the process
        console.error(" Error logging chat: ", err);
        process.exit(1);
    }
}
